name: radix_plus
description: A high-performance, in-place Radix Sort implementation for Dart and Flutter, providing significant speed improvements over standard sorting for number lists.
version: 1.0.3

license: GPL-version 3.0
topics: [sort, radix-sort, algorithm, flutter, dart]

repository: https://github.com/MostafaSensei106/Radix_Plus
homepage: https://github.com/MostafaSensei106/Radix_Plus
# funding: [https://github.com/sponsors/MostafaSensei106]

environment:
  sdk: ^3.10.1

dependencies:

dev_dependencies:
  benchmark_harness: ^2.3.1
  collection: ^1.19.1
  lints: ^6.0.0
  test: ^1.25.6
